knp_paginator:
    page_range: 5                      # Number of links showed in the pagination menu (e.g: you have 10 pages, a page_range of 3, on the 5th page you'll see links to page 4, 5, 6)
    default_options:
        page_name: page                # Pagina del parametro nella query string
        sort_field_name: sort          # Nome del parametro per il campo di ordinamento
        sort_direction_name: direction # Nome del parametro per la direzione di ordinamento
        distinct: true                 # Mantieni solo le voci distinte, utili quando si utilizzano join
    template:
        pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig' # Usa il tema di bootstrap 4
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'                      # Template per i link di ordinamento
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'                       # Template per la form di filtraggio
